Repository EjazaliRezayi/Instafeed, pull requests merged in 2021-03, with the labels that each got.

#9 Continuous integration
  .travis.yml
Labels: priority high

#15 #5 User is able to comment on a post
  node_modules/.cache/.eslintcache
  node_modules/.cache/babel-loader/001b8a1c2c26a5273cb350e2ad9b1f2b.json
  node_modules/.cache/babel-loader/04b4a074dcac839965f36f330eac7968.json
  node_modules/.cache/babel-loader/10f6b94c167b22e7ae4ebad4aaaa7fd2.json
  node_modules/.cache/babel-loader/111005b51a9a811bb65c1fe5cb5d2583.json
  node_modules/.cache/babel-loader/163ddac59fea03aa14c4e8eee621fad6.json
  node_modules/.cache/babel-loader/27b0712fb107425714e03ffad69cb121.json
  node_modules/.cache/babel-loader/3462a0895e0ae97e75723c22d5a161b2.json
  node_modules/.cache/babel-loader/35af8c10848a30533246bd8283ff91bf.json
  node_modules/.cache/babel-loader/3dca9cc6c61a86d903d56afa1b64044f.json
  node_modules/.cache/babel-loader/40be4ba539b2c8ae8e93c1d970d827e0.json
  node_modules/.cache/babel-loader/48db50b45f461a92f7b2f88e8b1a787e.json
  node_modules/.cache/babel-loader/58d10b71db657eb32311d1f528765d67.json
  node_modules/.cache/babel-loader/63ffb07867862d41f975c50d8fc7de8d.json
  node_modules/.cache/babel-loader/64c10a4f14911d76502394855c854bf4.json
  node_modules/.cache/babel-loader/6e9dd9ec90a5009530e5fa89fae4cb2c.json
  node_modules/.cache/babel-loader/71e8c4822fccbefc6c15bd6085608882.json
  node_modules/.cache/babel-loader/7229d704300e42e6c51ce2ce3e9b2fc0.json
  node_modules/.cache/babel-loader/7453ee07943c9f9705aeb697918a5f8f.json
  node_modules/.cache/babel-loader/76231954ceb7fff4a46d0b3b5c567c13.json
  node_modules/.cache/babel-loader/8b6a5a8e3db64c6584973841c640c5d1.json
  node_modules/.cache/babel-loader/9122496e3c1d4cd6ed633a6510b7ca2b.json
  node_modules/.cache/babel-loader/917160b7519e64215f8cdb00e3fe2fa5.json
  node_modules/.cache/babel-loader/99cdef9d923486d08f2386f30e14cd88.json
  node_modules/.cache/babel-loader/a12cf4536e2516ca6c4a2631dd51fff6.json
  node_modules/.cache/babel-loader/a365171f1355d8f4f4146439855a833f.json
  node_modules/.cache/babel-loader/aedf63d2d72857be694aef14cee33a43.json
  node_modules/.cache/babel-loader/b2112a89022e9ee458af4ac6e7539da1.json
  node_modules/.cache/babel-loader/b289c46eafba630b979b05371efcfb23.json
  node_modules/.cache/babel-loader/b36cfed01f0e0c366da26127c7df3bc0.json
  node_modules/.cache/babel-loader/b4ebc9d61fa8b3de078cc9e5c95f2005.json
  node_modules/.cache/babel-loader/cf7417b920e7bef8a0495f42a097e194.json
  node_modules/.cache/babel-loader/cf9e6ecae954a21e2c94548d90d543cf.json
  node_modules/.cache/babel-loader/d5891cd1f1d3af1425508afbbb7922e1.json
  node_modules/.cache/babel-loader/dad5677276b6a9c512fa557e57c70b50.json
  node_modules/.cache/babel-loader/db7d67c19df9701b1b6203f879e49b30.json
  node_modules/.cache/babel-loader/dcf70cc3ed04580ce6ea43cda43f3e20.json
  node_modules/.cache/babel-loader/df8125150650d6310e1e5e7137ce5cbe.json
  node_modules/.cache/babel-loader/e203f528bd6c32346c3602041637d661.json
  node_modules/.cache/babel-loader/e8900d2eb5c817157ff59aa946152a6f.json
  node_modules/.cache/babel-loader/eacc3d3d3665079227dd9c83e760de3e.json
  node_modules/.cache/babel-loader/ef88d95fafb89cdd23d2231fa51864e3.json
  node_modules/.cache/babel-loader/fad0dad518f38c056b7893175729d8b9.json
  node_modules/.cache/babel-loader/fbd2e6bc1d6801a55db737c374d1d65a.json
  src/App.css
  src/App.js
  src/Post.css
  src/Post.js
Labels: UserStory, priority high

#18 #4 Follow another user is now properly working
  node_modules/.cache/.eslintcache
  node_modules/.cache/babel-loader/00344d5307c1cfd257be6e9d5578d53a.json
  node_modules/.cache/babel-loader/050add8a14385d598867b6e366f97045.json
  node_modules/.cache/babel-loader/3c558d45ee4c4c2edb9b2362513d2d7a.json
  node_modules/.cache/babel-loader/3f82cdbc44123f4087f7731722c0edef.json
  node_modules/.cache/babel-loader/4a6082b1ab02617d47e2d1ddcf5c0ba5.json
  node_modules/.cache/babel-loader/4b0373777ff977c34c57fd503f7e2d07.json
  node_modules/.cache/babel-loader/5aa1aa8111cdd465c23110e7457bd265.json
  node_modules/.cache/babel-loader/5bf0ec525f64ce671e7c06646401fc87.json
  node_modules/.cache/babel-loader/620bff5c2887c0c6dd6f77a90e109e12.json
  node_modules/.cache/babel-loader/7873599c7011aef8fbcf6e792355a546.json
  node_modules/.cache/babel-loader/7add30f183db77ef8ab34f132154d6c3.json
  node_modules/.cache/babel-loader/80595afa38b807b18ab5ff4416e72770.json
  node_modules/.cache/babel-loader/bf652fa5e78a75f072be706d84ab91ac.json
  node_modules/.cache/babel-loader/cd0c2f8b8c15e9f8a987c2f826b4abd3.json
  node_modules/.cache/babel-loader/eac02ab19077e5ade8e26d94977d02c0.json
  node_modules/.cache/babel-loader/ee063c59bd1b601acf1237b83697e168.json
  src/App.js
  src/Post.css
  src/Post.js
Labels: UserStory, priority high, risk high
